/*
 * generated by Xtext 2.14.0
 */
package csy.tests

import com.google.inject.Inject
import csy.b.Abstraction
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(BInjectorProvider)
class BParsingTest {
	@Inject
	ParseHelper<Abstraction> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			MACHINE A
			END
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
