/*
 * generated by Xtext 2.14.0
 */
package csy

import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy
import csy.scoping.BResourceDescriptionStrategy

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class BRuntimeModule extends AbstractBRuntimeModule {
  def Class<? extends IDefaultResourceDescriptionStrategy> bindIDefaultResourceDescriptionStrategy() {
    return BResourceDescriptionStrategy;
  }
}
