/*
 * generated by Xtext 2.14.0
 */
package csy


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BStandaloneSetup extends BStandaloneSetupGenerated {

	def static void doSetup() {
		new BStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
