<?xml version="1.0" encoding="ISO-8859-1"?>
<ASPM:Model xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ASPM="http://jtl.univaq.it/aspm"
    ID="x_m1" name="x_b">
  <nodes ID="1" IDtrace="x_/" name="x_Machine"/>
  <nodes ID="4" IDtrace="x_//@operations/@operations.0/@body" name="x_Begin"/>
  <nodes ID="6" IDtrace="x_//@operations/@operations.1/@body" name="x_Begin"/>
  <nodes ID="5" IDtrace="x_//@operations/@operations.0/@body/@expr" name="x_ReturnTypeExpr"/>
  <nodes ID="7" IDtrace="x_//@operations/@operations.1/@body/@expr" name="x_ReturnTypeExpr"/>
  <nodes ID="9" IDtrace="x_//@operations/@operations.0/@body/@expr/@type" name="x_Ref"/>
  <nodes ID="12" IDtrace="x_//@operations/@operations.1/@body/@expr/@type" name="x_Ref"/>
  <edges ID="102" IDtrace="x_/101" name="x_operations" source="1" sourceTrace="x_/"
      targetTrace="x_//@operations"/>
  <edges ID="104" IDtrace="x_/103" name="x_sets" source="1" sourceTrace="x_/" targetTrace="x_//@sets"/>
  <edges ID="408" IDtrace="x_//@operations/@operations.0/@body407" name="x_expr" source="4"
      sourceTrace="x_//@operations/@operations.0/@body" target="5" targetTrace="x_//@operations/@operations.0/@body/@expr"/>
  <edges ID="6010" IDtrace="x_//@operations/@operations.1/@body609" name="x_expr"
      source="6" sourceTrace="x_//@operations/@operations.1/@body" target="7" targetTrace="x_//@operations/@operations.1/@body/@expr"/>
  <edges ID="5012" IDtrace="x_//@operations/@operations.0/@body/@expr5011" name="x_var"
      source="5" sourceTrace="x_//@operations/@operations.0/@body/@expr" targetTrace="x_//@operations/@operations.0/@outputs.0"/>
  <edges ID="5014" IDtrace="x_//@operations/@operations.0/@body/@expr5013" name="x_type"
      source="5" sourceTrace="x_//@operations/@operations.0/@body/@expr" target="9"
      targetTrace="x_//@operations/@operations.0/@body/@expr/@type"/>
  <edges ID="7016" IDtrace="x_//@operations/@operations.1/@body/@expr7015" name="x_var"
      source="7" sourceTrace="x_//@operations/@operations.1/@body/@expr" targetTrace="x_//@operations/@operations.1/@outputs.0"/>
  <edges ID="7018" IDtrace="x_//@operations/@operations.1/@body/@expr7017" name="x_type"
      source="7" sourceTrace="x_//@operations/@operations.1/@body/@expr" target="12"
      targetTrace="x_//@operations/@operations.1/@body/@expr/@type"/>
  <edges ID="9020" IDtrace="x_//@operations/@operations.0/@body/@expr/@type9019" name="x_type"
      source="9" sourceTrace="x_//@operations/@operations.0/@body/@expr/@type" targetTrace="x_//@sets/@exprs.0/@name"/>
  <edges ID="12022" IDtrace="x_//@operations/@operations.1/@body/@expr/@type12021"
      name="x_type" source="12" sourceTrace="x_//@operations/@operations.1/@body/@expr/@type"
      targetTrace="x_//@sets/@exprs.1/@name"/>
  <props ID="106" IDtrace="x_/105" name="x_name" value="x_Train" owner="1" ownerTrace="x_/"/>
</ASPM:Model>
