<?xml version="1.0" encoding="ISO-8859-1"?>
<ASPM:Model xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ASPM="http://jtl.univaq.it/aspm"
    ID="x_m1" name="x_b">
  <nodes ID="1" IDtrace="x_/" name="x_Machine"/>
  <nodes ID="5" IDtrace="x_//@concreteVariables" name="x_ConcreteVariables"/>
  <nodes ID="13" IDtrace="x_//@concreteConstants/@constants.0" name="x_Variable"/>
  <nodes ID="14" IDtrace="x_//@concreteConstants/@constants.1" name="x_Variable"/>
  <nodes ID="15" IDtrace="x_//@operations/@operations.0/@args.0" name="x_Variable"/>
  <nodes ID="16" IDtrace="x_//@operations/@operations.0/@args.1" name="x_Variable"/>
  <nodes ID="17" IDtrace="x_//@operations/@operations.0/@args.2" name="x_Variable"/>
  <nodes ID="18" IDtrace="x_//@operations/@operations.1/@args.0" name="x_Variable"/>
  <nodes ID="19" IDtrace="x_//@operations/@operations.1/@args.1" name="x_Variable"/>
  <nodes ID="21" IDtrace="x_//@operations/@operations.1/@args.2" name="x_Variable"/>
  <nodes ID="9" IDtrace="x_//@concreteVariables/@variables.0" name="x_Variable"/>
  <nodes ID="11" IDtrace="x_//@concreteVariables/@variables.1" name="x_Variable"/>
  <nodes ID="12" IDtrace="x_//@concreteVariables/@variables.2" name="x_Variable"/>
  <nodes ID="2" IDtrace="x_//@concreteConstants" name="x_ConcreteConstants"/>
  <nodes ID="6" IDtrace="x_//@invariant" name="x_Invariant"/>
  <nodes ID="22" IDtrace="x_//@invariant/@exprs.0" name="x_InvariantExpr"/>
  <nodes ID="23" IDtrace="x_//@invariant/@exprs.1" name="x_InvariantExpr"/>
  <nodes ID="24" IDtrace="x_//@invariant/@exprs.2" name="x_InvariantExpr"/>
  <nodes ID="7" IDtrace="x_//@initialisation" name="x_Initialisation"/>
  <nodes ID="28" IDtrace="x_//@initialisation/@exprs.0" name="x_InitialisationExpr"/>
  <nodes ID="29" IDtrace="x_//@initialisation/@exprs.1" name="x_InitialisationExpr"/>
  <nodes ID="31" IDtrace="x_//@initialisation/@exprs.2" name="x_InitialisationExpr"/>
  <nodes ID="3" IDtrace="x_//@properties" name="x_Properties"/>
  <nodes ID="37" IDtrace="x_//@properties/@expr.0/@range" name="x_Range"/>
  <nodes ID="8" IDtrace="x_//@assertions" name="x_Assertions"/>
  <nodes ID="38" IDtrace="x_//@assertions/@exprs.0" name="x_AssertionExpr"/>
  <nodes ID="4" IDtrace="x_//@operations" name="x_Operations"/>
  <nodes ID="41" IDtrace="x_//@operations/@operations.0" name="x_Operation"/>
  <nodes ID="42" IDtrace="x_//@operations/@operations.1" name="x_Operation"/>
  <nodes ID="43" IDtrace="x_//@operations/@operations.2" name="x_Operation"/>
  <nodes ID="47" IDtrace="x_//@operations/@operations.0/@body/@expr" name="x_Skip"/>
  <nodes ID="48" IDtrace="x_//@operations/@operations.1/@body/@expr" name="x_Skip"/>
  <nodes ID="46" IDtrace="x_//@operations/@operations.2/@body" name="x_Skip"/>
  <nodes ID="44" IDtrace="x_//@operations/@operations.0/@body" name="x_Pre"/>
  <nodes ID="45" IDtrace="x_//@operations/@operations.1/@body" name="x_Pre"/>
  <nodes ID="49" IDtrace="x_//@operations/@operations.0/@body/@exprs.0" name="x_PreExpr"/>
  <nodes ID="51" IDtrace="x_//@operations/@operations.0/@body/@exprs.1" name="x_PreExpr"/>
  <nodes ID="52" IDtrace="x_//@operations/@operations.0/@body/@exprs.2" name="x_PreExpr"/>
  <nodes ID="53" IDtrace="x_//@operations/@operations.1/@body/@exprs.0" name="x_PreExpr"/>
  <nodes ID="54" IDtrace="x_//@operations/@operations.1/@body/@exprs.1" name="x_PreExpr"/>
  <nodes ID="55" IDtrace="x_//@operations/@operations.1/@body/@exprs.2" name="x_PreExpr"/>
  <nodes ID="63" IDtrace="x_//@properties/@exprs.0/@type" name="x_PrimitiveType"/>
  <nodes ID="56" IDtrace="x_//@operations/@operations.0/@body/@exprs.0/@type" name="x_PrimitiveType"/>
  <nodes ID="57" IDtrace="x_//@operations/@operations.0/@body/@exprs.1/@type" name="x_PrimitiveType"/>
  <nodes ID="58" IDtrace="x_//@operations/@operations.0/@body/@exprs.2/@type" name="x_PrimitiveType"/>
  <nodes ID="59" IDtrace="x_//@operations/@operations.1/@body/@exprs.0/@type" name="x_PrimitiveType"/>
  <nodes ID="61" IDtrace="x_//@operations/@operations.1/@body/@exprs.1/@type" name="x_PrimitiveType"/>
  <nodes ID="62" IDtrace="x_//@operations/@operations.1/@body/@exprs.2/@type" name="x_PrimitiveType"/>
  <nodes ID="25" IDtrace="x_//@invariant/@exprs.0/@type" name="x_PrimitiveType"/>
  <nodes ID="26" IDtrace="x_//@invariant/@exprs.1/@type" name="x_PrimitiveType"/>
  <nodes ID="27" IDtrace="x_//@invariant/@exprs.2/@type" name="x_PrimitiveType"/>
  <nodes ID="32" IDtrace="x_//@initialisation/@exprs.0/@type" name="x_PrimitiveType"/>
  <nodes ID="33" IDtrace="x_//@initialisation/@exprs.1/@type" name="x_PrimitiveType"/>
  <nodes ID="34" IDtrace="x_//@initialisation/@exprs.2/@type" name="x_PrimitiveType"/>
  <nodes ID="39" IDtrace="x_//@assertions/@exprs.0/@type" name="x_PrimitiveType"/>
  <nodes ID="35" IDtrace="x_//@properties/@exprs.0" name="x_PropertyTyped"/>
  <nodes ID="36" IDtrace="x_//@properties/@expr.0" name="x_PropertyRange"/>
  <edges ID="102" IDtrace="x_/101" name="x_concreteConstants" source="1" sourceTrace="x_/"
      target="2" targetTrace="x_//@concreteConstants"/>
  <edges ID="104" IDtrace="x_/103" name="x_properties" source="1" sourceTrace="x_/"
      target="3" targetTrace="x_//@properties"/>
  <edges ID="106" IDtrace="x_/105" name="x_operations" source="1" sourceTrace="x_/"
      target="4" targetTrace="x_//@operations"/>
  <edges ID="108" IDtrace="x_/107" name="x_concreteVariables" source="1" sourceTrace="x_/"
      target="5" targetTrace="x_//@concreteVariables"/>
  <edges ID="1010" IDtrace="x_/109" name="x_invariant" source="1" sourceTrace="x_/"
      target="6" targetTrace="x_//@invariant"/>
  <edges ID="1012" IDtrace="x_/1011" name="x_initialisation" source="1" sourceTrace="x_/"
      target="7" targetTrace="x_//@initialisation"/>
  <edges ID="1014" IDtrace="x_/1013" name="x_assertions" source="1" sourceTrace="x_/"
      target="8" targetTrace="x_//@assertions"/>
  <edges ID="5018" IDtrace="x_//@concreteVariables5017" name="x_variables" source="5"
      sourceTrace="x_//@concreteVariables" target="9" targetTrace="x_//@concreteVariables/@variables.0"/>
  <edges ID="5020" IDtrace="x_//@concreteVariables5019" name="x_variables" source="5"
      sourceTrace="x_//@concreteVariables" target="11" targetTrace="x_//@concreteVariables/@variables.1"/>
  <edges ID="5022" IDtrace="x_//@concreteVariables5021" name="x_variables" source="5"
      sourceTrace="x_//@concreteVariables" target="12" targetTrace="x_//@concreteVariables/@variables.2"/>
  <edges ID="2046" IDtrace="x_//@concreteConstants2045" name="x_constants" source="2"
      sourceTrace="x_//@concreteConstants" target="13" targetTrace="x_//@concreteConstants/@constants.0"/>
  <edges ID="2048" IDtrace="x_//@concreteConstants2047" name="x_constants" source="2"
      sourceTrace="x_//@concreteConstants" target="14" targetTrace="x_//@concreteConstants/@constants.1"/>
  <edges ID="6050" IDtrace="x_//@invariant6049" name="x_exprs" source="6" sourceTrace="x_//@invariant"
      target="22" targetTrace="x_//@invariant/@exprs.0"/>
  <edges ID="6052" IDtrace="x_//@invariant6051" name="x_exprs" source="6" sourceTrace="x_//@invariant"
      target="23" targetTrace="x_//@invariant/@exprs.1"/>
  <edges ID="6054" IDtrace="x_//@invariant6053" name="x_exprs" source="6" sourceTrace="x_//@invariant"
      target="24" targetTrace="x_//@invariant/@exprs.2"/>
  <edges ID="22056" IDtrace="x_//@invariant/@exprs.022055" name="x_variable" source="22"
      sourceTrace="x_//@invariant/@exprs.0" target="9" targetTrace="x_//@concreteVariables/@variables.0"/>
  <edges ID="22058" IDtrace="x_//@invariant/@exprs.022057" name="x_type" source="22"
      sourceTrace="x_//@invariant/@exprs.0" target="25" targetTrace="x_//@invariant/@exprs.0/@type"/>
  <edges ID="23060" IDtrace="x_//@invariant/@exprs.123059" name="x_variable" source="23"
      sourceTrace="x_//@invariant/@exprs.1" target="11" targetTrace="x_//@concreteVariables/@variables.1"/>
  <edges ID="23062" IDtrace="x_//@invariant/@exprs.123061" name="x_type" source="23"
      sourceTrace="x_//@invariant/@exprs.1" target="26" targetTrace="x_//@invariant/@exprs.1/@type"/>
  <edges ID="24064" IDtrace="x_//@invariant/@exprs.224063" name="x_variable" source="24"
      sourceTrace="x_//@invariant/@exprs.2" target="12" targetTrace="x_//@concreteVariables/@variables.2"/>
  <edges ID="24066" IDtrace="x_//@invariant/@exprs.224065" name="x_type" source="24"
      sourceTrace="x_//@invariant/@exprs.2" target="27" targetTrace="x_//@invariant/@exprs.2/@type"/>
  <edges ID="7068" IDtrace="x_//@initialisation7067" name="x_exprs" source="7" sourceTrace="x_//@initialisation"
      target="28" targetTrace="x_//@initialisation/@exprs.0"/>
  <edges ID="7070" IDtrace="x_//@initialisation7069" name="x_exprs" source="7" sourceTrace="x_//@initialisation"
      target="29" targetTrace="x_//@initialisation/@exprs.1"/>
  <edges ID="7072" IDtrace="x_//@initialisation7071" name="x_exprs" source="7" sourceTrace="x_//@initialisation"
      target="31" targetTrace="x_//@initialisation/@exprs.2"/>
  <edges ID="28074" IDtrace="x_//@initialisation/@exprs.028073" name="x_variable"
      source="28" sourceTrace="x_//@initialisation/@exprs.0" target="9" targetTrace="x_//@concreteVariables/@variables.0"/>
  <edges ID="28076" IDtrace="x_//@initialisation/@exprs.028075" name="x_type" source="28"
      sourceTrace="x_//@initialisation/@exprs.0" target="32" targetTrace="x_//@initialisation/@exprs.0/@type"/>
  <edges ID="29078" IDtrace="x_//@initialisation/@exprs.129077" name="x_variable"
      source="29" sourceTrace="x_//@initialisation/@exprs.1" target="11" targetTrace="x_//@concreteVariables/@variables.1"/>
  <edges ID="29080" IDtrace="x_//@initialisation/@exprs.129079" name="x_type" source="29"
      sourceTrace="x_//@initialisation/@exprs.1" target="33" targetTrace="x_//@initialisation/@exprs.1/@type"/>
  <edges ID="31082" IDtrace="x_//@initialisation/@exprs.231081" name="x_variable"
      source="31" sourceTrace="x_//@initialisation/@exprs.2" target="12" targetTrace="x_//@concreteVariables/@variables.2"/>
  <edges ID="31084" IDtrace="x_//@initialisation/@exprs.231083" name="x_type" source="31"
      sourceTrace="x_//@initialisation/@exprs.2" target="34" targetTrace="x_//@initialisation/@exprs.2/@type"/>
  <edges ID="3086" IDtrace="x_//@properties3085" name="x_exprs" source="3" sourceTrace="x_//@properties"
      target="35" targetTrace="x_//@properties/@exprs.0"/>
  <edges ID="3088" IDtrace="x_//@properties3087" name="x_expr" source="3" sourceTrace="x_//@properties"
      target="36" targetTrace="x_//@properties/@expr.0"/>
  <edges ID="37090" IDtrace="x_//@properties/@expr.0/@range37089" name="x_upperBound"
      source="37" sourceTrace="x_//@properties/@expr.0/@range" target="13" targetTrace="x_//@concreteConstants/@constants.0"/>
  <edges ID="8092" IDtrace="x_//@assertions8091" name="x_exprs" source="8" sourceTrace="x_//@assertions"
      target="38" targetTrace="x_//@assertions/@exprs.0"/>
  <edges ID="38094" IDtrace="x_//@assertions/@exprs.038093" name="x_constant" source="38"
      sourceTrace="x_//@assertions/@exprs.0" target="14" targetTrace="x_//@concreteConstants/@constants.1"/>
  <edges ID="38096" IDtrace="x_//@assertions/@exprs.038095" name="x_type" source="38"
      sourceTrace="x_//@assertions/@exprs.0" target="39" targetTrace="x_//@assertions/@exprs.0/@type"/>
  <edges ID="4098" IDtrace="x_//@operations4097" name="x_operations" source="4" sourceTrace="x_//@operations"
      target="41" targetTrace="x_//@operations/@operations.0"/>
  <edges ID="40100" IDtrace="x_//@operations4099" name="x_operations" source="4" sourceTrace="x_//@operations"
      target="42" targetTrace="x_//@operations/@operations.1"/>
  <edges ID="40102" IDtrace="x_//@operations40101" name="x_operations" source="4"
      sourceTrace="x_//@operations" target="43" targetTrace="x_//@operations/@operations.2"/>
  <edges ID="410104" IDtrace="x_//@operations/@operations.0410103" name="x_args" source="41"
      sourceTrace="x_//@operations/@operations.0" target="15" targetTrace="x_//@operations/@operations.0/@args.0"/>
  <edges ID="410106" IDtrace="x_//@operations/@operations.0410105" name="x_args" source="41"
      sourceTrace="x_//@operations/@operations.0" target="16" targetTrace="x_//@operations/@operations.0/@args.1"/>
  <edges ID="410108" IDtrace="x_//@operations/@operations.0410107" name="x_args" source="41"
      sourceTrace="x_//@operations/@operations.0" target="17" targetTrace="x_//@operations/@operations.0/@args.2"/>
  <edges ID="410110" IDtrace="x_//@operations/@operations.0410109" name="x_body" source="41"
      sourceTrace="x_//@operations/@operations.0" target="44" targetTrace="x_//@operations/@operations.0/@body"/>
  <edges ID="420114" IDtrace="x_//@operations/@operations.1420113" name="x_args" source="42"
      sourceTrace="x_//@operations/@operations.1" target="18" targetTrace="x_//@operations/@operations.1/@args.0"/>
  <edges ID="420116" IDtrace="x_//@operations/@operations.1420115" name="x_args" source="42"
      sourceTrace="x_//@operations/@operations.1" target="19" targetTrace="x_//@operations/@operations.1/@args.1"/>
  <edges ID="420118" IDtrace="x_//@operations/@operations.1420117" name="x_args" source="42"
      sourceTrace="x_//@operations/@operations.1" target="21" targetTrace="x_//@operations/@operations.1/@args.2"/>
  <edges ID="420120" IDtrace="x_//@operations/@operations.1420119" name="x_body" source="42"
      sourceTrace="x_//@operations/@operations.1" target="45" targetTrace="x_//@operations/@operations.1/@body"/>
  <edges ID="430124" IDtrace="x_//@operations/@operations.2430123" name="x_body" source="43"
      sourceTrace="x_//@operations/@operations.2" target="46" targetTrace="x_//@operations/@operations.2/@body"/>
  <edges ID="440128" IDtrace="x_//@operations/@operations.0/@body440127" name="x_exprs"
      source="44" sourceTrace="x_//@operations/@operations.0/@body" target="49" targetTrace="x_//@operations/@operations.0/@body/@exprs.0"/>
  <edges ID="440130" IDtrace="x_//@operations/@operations.0/@body440129" name="x_exprs"
      source="44" sourceTrace="x_//@operations/@operations.0/@body" target="51" targetTrace="x_//@operations/@operations.0/@body/@exprs.1"/>
  <edges ID="440132" IDtrace="x_//@operations/@operations.0/@body440131" name="x_exprs"
      source="44" sourceTrace="x_//@operations/@operations.0/@body" target="52" targetTrace="x_//@operations/@operations.0/@body/@exprs.2"/>
  <edges ID="440134" IDtrace="x_//@operations/@operations.0/@body440133" name="x_expr"
      source="44" sourceTrace="x_//@operations/@operations.0/@body" target="47" targetTrace="x_//@operations/@operations.0/@body/@expr"/>
  <edges ID="450136" IDtrace="x_//@operations/@operations.1/@body450135" name="x_exprs"
      source="45" sourceTrace="x_//@operations/@operations.1/@body" target="53" targetTrace="x_//@operations/@operations.1/@body/@exprs.0"/>
  <edges ID="450138" IDtrace="x_//@operations/@operations.1/@body450137" name="x_exprs"
      source="45" sourceTrace="x_//@operations/@operations.1/@body" target="54" targetTrace="x_//@operations/@operations.1/@body/@exprs.1"/>
  <edges ID="450140" IDtrace="x_//@operations/@operations.1/@body450139" name="x_exprs"
      source="45" sourceTrace="x_//@operations/@operations.1/@body" target="55" targetTrace="x_//@operations/@operations.1/@body/@exprs.2"/>
  <edges ID="450142" IDtrace="x_//@operations/@operations.1/@body450141" name="x_expr"
      source="45" sourceTrace="x_//@operations/@operations.1/@body" target="48" targetTrace="x_//@operations/@operations.1/@body/@expr"/>
  <edges ID="490144" IDtrace="x_//@operations/@operations.0/@body/@exprs.0490143"
      name="x_var" source="49" sourceTrace="x_//@operations/@operations.0/@body/@exprs.0"
      target="15" targetTrace="x_//@operations/@operations.0/@args.0"/>
  <edges ID="490146" IDtrace="x_//@operations/@operations.0/@body/@exprs.0490145"
      name="x_type" source="49" sourceTrace="x_//@operations/@operations.0/@body/@exprs.0"
      target="56" targetTrace="x_//@operations/@operations.0/@body/@exprs.0/@type"/>
  <edges ID="510148" IDtrace="x_//@operations/@operations.0/@body/@exprs.1510147"
      name="x_var" source="51" sourceTrace="x_//@operations/@operations.0/@body/@exprs.1"
      target="16" targetTrace="x_//@operations/@operations.0/@args.1"/>
  <edges ID="510150" IDtrace="x_//@operations/@operations.0/@body/@exprs.1510149"
      name="x_type" source="51" sourceTrace="x_//@operations/@operations.0/@body/@exprs.1"
      target="57" targetTrace="x_//@operations/@operations.0/@body/@exprs.1/@type"/>
  <edges ID="520152" IDtrace="x_//@operations/@operations.0/@body/@exprs.2520151"
      name="x_var" source="52" sourceTrace="x_//@operations/@operations.0/@body/@exprs.2"
      target="17" targetTrace="x_//@operations/@operations.0/@args.2"/>
  <edges ID="520154" IDtrace="x_//@operations/@operations.0/@body/@exprs.2520153"
      name="x_type" source="52" sourceTrace="x_//@operations/@operations.0/@body/@exprs.2"
      target="58" targetTrace="x_//@operations/@operations.0/@body/@exprs.2/@type"/>
  <edges ID="530156" IDtrace="x_//@operations/@operations.1/@body/@exprs.0530155"
      name="x_var" source="53" sourceTrace="x_//@operations/@operations.1/@body/@exprs.0"
      target="18" targetTrace="x_//@operations/@operations.1/@args.0"/>
  <edges ID="530158" IDtrace="x_//@operations/@operations.1/@body/@exprs.0530157"
      name="x_type" source="53" sourceTrace="x_//@operations/@operations.1/@body/@exprs.0"
      target="59" targetTrace="x_//@operations/@operations.1/@body/@exprs.0/@type"/>
  <edges ID="540160" IDtrace="x_//@operations/@operations.1/@body/@exprs.1540159"
      name="x_var" source="54" sourceTrace="x_//@operations/@operations.1/@body/@exprs.1"
      target="19" targetTrace="x_//@operations/@operations.1/@args.1"/>
  <edges ID="540162" IDtrace="x_//@operations/@operations.1/@body/@exprs.1540161"
      name="x_type" source="54" sourceTrace="x_//@operations/@operations.1/@body/@exprs.1"
      target="61" targetTrace="x_//@operations/@operations.1/@body/@exprs.1/@type"/>
  <edges ID="550164" IDtrace="x_//@operations/@operations.1/@body/@exprs.2550163"
      name="x_var" source="55" sourceTrace="x_//@operations/@operations.1/@body/@exprs.2"
      target="21" targetTrace="x_//@operations/@operations.1/@args.2"/>
  <edges ID="550166" IDtrace="x_//@operations/@operations.1/@body/@exprs.2550165"
      name="x_type" source="55" sourceTrace="x_//@operations/@operations.1/@body/@exprs.2"
      target="62" targetTrace="x_//@operations/@operations.1/@body/@exprs.2/@type"/>
  <edges ID="350196" IDtrace="x_//@properties/@exprs.0350195" name="x_constant" source="35"
      sourceTrace="x_//@properties/@exprs.0" target="13" targetTrace="x_//@concreteConstants/@constants.0"/>
  <edges ID="350198" IDtrace="x_//@properties/@exprs.0350197" name="x_type" source="35"
      sourceTrace="x_//@properties/@exprs.0" target="63" targetTrace="x_//@properties/@exprs.0/@type"/>
  <edges ID="360200" IDtrace="x_//@properties/@expr.0360199" name="x_constant" source="36"
      sourceTrace="x_//@properties/@expr.0" target="14" targetTrace="x_//@concreteConstants/@constants.1"/>
  <edges ID="360202" IDtrace="x_//@properties/@expr.0360201" name="x_range" source="36"
      sourceTrace="x_//@properties/@expr.0" target="37" targetTrace="x_//@properties/@expr.0/@range"/>
  <props ID="1016" IDtrace="x_/1015" name="x_name" value="x_Utils" owner="1" ownerTrace="x_/"/>
  <props ID="13024" IDtrace="x_//@concreteConstants/@constants.013023" name="x_name"
      value="x_UINT16_MAX" owner="13" ownerTrace="x_//@concreteConstants/@constants.0"/>
  <props ID="14026" IDtrace="x_//@concreteConstants/@constants.114025" name="x_name"
      value="x_uint16_t" owner="14" ownerTrace="x_//@concreteConstants/@constants.1"/>
  <props ID="15028" IDtrace="x_//@operations/@operations.0/@args.015027" name="x_name"
      value="x_sensor" owner="15" ownerTrace="x_//@operations/@operations.0/@args.0"/>
  <props ID="16030" IDtrace="x_//@operations/@operations.0/@args.116029" name="x_name"
      value="x_variable" owner="16" ownerTrace="x_//@operations/@operations.0/@args.1"/>
  <props ID="17032" IDtrace="x_//@operations/@operations.0/@args.217031" name="x_name"
      value="x_value" owner="17" ownerTrace="x_//@operations/@operations.0/@args.2"/>
  <props ID="18034" IDtrace="x_//@operations/@operations.1/@args.018033" name="x_name"
      value="x_sensor" owner="18" ownerTrace="x_//@operations/@operations.1/@args.0"/>
  <props ID="19036" IDtrace="x_//@operations/@operations.1/@args.119035" name="x_name"
      value="x_variable" owner="19" ownerTrace="x_//@operations/@operations.1/@args.1"/>
  <props ID="21038" IDtrace="x_//@operations/@operations.1/@args.221037" name="x_name"
      value="x_value" owner="21" ownerTrace="x_//@operations/@operations.1/@args.2"/>
  <props ID="9040" IDtrace="x_//@concreteVariables/@variables.09039" name="x_name"
      value="x_current_date" owner="9" ownerTrace="x_//@concreteVariables/@variables.0"/>
  <props ID="11042" IDtrace="x_//@concreteVariables/@variables.111041" name="x_name"
      value="x_current_time" owner="11" ownerTrace="x_//@concreteVariables/@variables.1"/>
  <props ID="12044" IDtrace="x_//@concreteVariables/@variables.212043" name="x_name"
      value="x_toprint" owner="12" ownerTrace="x_//@concreteVariables/@variables.2"/>
  <props ID="410112" IDtrace="x_//@operations/@operations.0410111" name="x_name" value="x_print"
      owner="41" ownerTrace="x_//@operations/@operations.0"/>
  <props ID="420122" IDtrace="x_//@operations/@operations.1420121" name="x_name" value="x_urgent_print"
      owner="42" ownerTrace="x_//@operations/@operations.1"/>
  <props ID="430126" IDtrace="x_//@operations/@operations.2430125" name="x_name" value="x_flush"
      owner="43" ownerTrace="x_//@operations/@operations.2"/>
  <props ID="630168" IDtrace="x_//@properties/@exprs.0/@type630167" name="x_type"
      value="x_b!NAT1" owner="63" ownerTrace="x_//@properties/@exprs.0/@type"/>
  <props ID="560170" IDtrace="x_//@operations/@operations.0/@body/@exprs.0/@type560169"
      name="x_type" value="x_b!STRING" owner="56" ownerTrace="x_//@operations/@operations.0/@body/@exprs.0/@type"/>
  <props ID="570172" IDtrace="x_//@operations/@operations.0/@body/@exprs.1/@type570171"
      name="x_type" value="x_b!STRING" owner="57" ownerTrace="x_//@operations/@operations.0/@body/@exprs.1/@type"/>
  <props ID="580174" IDtrace="x_//@operations/@operations.0/@body/@exprs.2/@type580173"
      name="x_type" value="x_b!STRING" owner="58" ownerTrace="x_//@operations/@operations.0/@body/@exprs.2/@type"/>
  <props ID="590176" IDtrace="x_//@operations/@operations.1/@body/@exprs.0/@type590175"
      name="x_type" value="x_b!STRING" owner="59" ownerTrace="x_//@operations/@operations.1/@body/@exprs.0/@type"/>
  <props ID="610178" IDtrace="x_//@operations/@operations.1/@body/@exprs.1/@type610177"
      name="x_type" value="x_b!STRING" owner="61" ownerTrace="x_//@operations/@operations.1/@body/@exprs.1/@type"/>
  <props ID="620180" IDtrace="x_//@operations/@operations.1/@body/@exprs.2/@type620179"
      name="x_type" value="x_b!STRING" owner="62" ownerTrace="x_//@operations/@operations.1/@body/@exprs.2/@type"/>
  <props ID="250182" IDtrace="x_//@invariant/@exprs.0/@type250181" name="x_type" value="x_b!INT"
      owner="25" ownerTrace="x_//@invariant/@exprs.0/@type"/>
  <props ID="260184" IDtrace="x_//@invariant/@exprs.1/@type260183" name="x_type" value="x_b!INT"
      owner="26" ownerTrace="x_//@invariant/@exprs.1/@type"/>
  <props ID="270186" IDtrace="x_//@invariant/@exprs.2/@type270185" name="x_type" value="x_b!BOOL"
      owner="27" ownerTrace="x_//@invariant/@exprs.2/@type"/>
  <props ID="320188" IDtrace="x_//@initialisation/@exprs.0/@type320187" name="x_type"
      value="x_b!INT" owner="32" ownerTrace="x_//@initialisation/@exprs.0/@type"/>
  <props ID="330190" IDtrace="x_//@initialisation/@exprs.1/@type330189" name="x_type"
      value="x_b!INT" owner="33" ownerTrace="x_//@initialisation/@exprs.1/@type"/>
  <props ID="340192" IDtrace="x_//@initialisation/@exprs.2/@type340191" name="x_type"
      value="x_b!BOOL" owner="34" ownerTrace="x_//@initialisation/@exprs.2/@type"/>
  <props ID="390194" IDtrace="x_//@assertions/@exprs.0/@type390193" name="x_type"
      value="x_b!INT" owner="39" ownerTrace="x_//@assertions/@exprs.0/@type"/>
</ASPM:Model>
