/*
 * generated by Xtext 2.14.0
 */
package csy.ide

import com.google.inject.Guice
import csy.BRuntimeModule
import csy.BStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class BIdeSetup extends BStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new BRuntimeModule, new BIdeModule))
	}
	
}
